import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { areCalculationAnswersCorrect, calculationBlankIndexes, formatCalculationAnswers, isCalculationAnswerCorrect, normalizeCalculationAnswer, validateCalculationBlankLayout } from "../../src/lib/question/question-utils";

const read = (path: string) => readFileSync(new URL(`../../${path}`, import.meta.url), "utf8");
const studyApp = read("src/app/shell/app-shell.tsx");
const practiceView = read("src/app/shell/views/practice.tsx");
const history = read("src/app/practice/practice-history.tsx");
const editor = read("src/app/bank/question-editor.tsx");
const contentEditor = read("src/app/bank/content-block-editor.tsx");
const xlsx = read("src/lib/io/xlsx-import.ts");
const vite = read("vite.config.ts");

assert.equal(normalizeCalculationAnswer(" 12.50 "), "12.50");
assert.equal(normalizeCalculationAnswer([" 11.0 ", "968.0"]), "11.0\n968.0");
assert.throws(() => normalizeCalculationAnswer("十二"), /有效数字/);
assert.deepEqual(calculationBlankIndexes("电流【空1】A，功率【空2】W"), [1, 2]);
assert.doesNotThrow(() => validateCalculationBlankLayout("电流【空1】A，功率【空2】W", "11\n968"));
assert.throws(() => validateCalculationBlankLayout("电流【空1】A", "11\n968"), /1 个填空.*2 个标准答案/);
assert.equal(formatCalculationAnswers("11\n968"), "第1空：11；第2空：968");
assert.equal(isCalculationAnswerCorrect("100.9", "100", 1), true);
assert.equal(isCalculationAnswerCorrect("101.1", "100", 1), false);
assert.equal(isCalculationAnswerCorrect("0.005", "0", 1), true);
assert.equal(isCalculationAnswerCorrect("0.02", "0", 1), false);
assert.equal(areCalculationAnswersCorrect(["11.05", "970"], "11\n968", 1), true);
assert.equal(areCalculationAnswersCorrect(["11.05", "980"], "11\n968", 1), false);
assert.equal(areCalculationAnswersCorrect(["11.05"], "11\n968", 1), false);
assert.match(editor, /questionTypes[^\n]*"计算"/, "question editor must expose calculation questions");
assert.match(editor, /optimizeImageFile/, "question editor must optimize selected local images");
assert.match(editor, /putImageAssetV7/, "question editor must store content-addressed image assets");
assert.match(contentEditor, /accept="image\/\*"/, "rich content editor must select a local image file");
assert.match(contentEditor, /insertImageAtSelection/, "rich content editor must insert images at the current text selection");
assert.doesNotMatch(editor, /题目图片地址|imageUrl/, "question editor must not accept public image URLs");
assert.match(xlsx, /"题干", "题型", "标签", "解析"/, "Excel parser must use the redesigned base columns");
assert.match(xlsx, /ANSWER_HEADER_PATTERN/, "Excel parser must recognise positional 答案N columns");
assert.doesNotMatch(xlsx, /图片地址/, "Excel imports must not accept public image URLs");
assert.match(practiceView, /CalculationContentRenderer/, "practice must render positional calculation blank inputs");
assert.match(practiceView, /areCalculationAnswersCorrect/, "practice must grade every calculation blank");
assert.match(practiceView, /calculationTolerancePercent/, "calculation grading must consume the configured tolerance");
assert.doesNotMatch(practiceView, /依次填写题干中的/, "inline calculation blanks must not repeat guidance in a separate card");
assert.match(practiceView, /question\.type === "计算" \? !hasInlineCalculationBlanks && <div className=\{`calculation-answer fallback-grid/, "only legacy calculations without inline blanks should render the fallback answer card");
assert.match(practiceView, /window\.setTimeout\(\(\) => void persistNoteDraft\(\), 650\)/, "notes must auto-save after a short debounce");
assert.match(practiceView, /if \(noteDirty\.current\) void saveNote\(question\.id, draftRef\.current\)/, "leaving a question must flush a dirty note");
assert.match(studyApp, /randomOptionOrder\(question, avoidOptionOrders\?\.\[question\.id\]\)/, "repeating a run must avoid its previous option order");
assert.match(history, /setDetailQuestion\(question\)/, "completed result rows must open question details");
assert.doesNotMatch(history, /disabled=\{!canContinue\}/, "completed result rows must remain interactive");
assert.match(vite, /__APP_COMMIT_SHA__/, "build must inject its commit hash");
assert.match(vite, /__APP_COMMIT_TIME__/, "build must inject its commit timestamp");

console.log("question feature tests passed: images, calculation tolerance, result details, reshuffle, note autosave and build version");
