// 测试分组与 npm script 的唯一映射。新增测试后只需在这里登记，
// package.json 的 test:unit / test:source / test:integration 不再各自罗列。
export const testGroups = {
  unit: [
    "test:active-elapsed",
    "test:history-sync-range",
    "test:notice-tone",
    "test:shortcuts",
    "test:xlsx",
    "test:note-markdown",
    "test:press-intent",
    "test:typography",
    "test:overview",
    "test:progress-boundaries",
    "test:projection-edge",
    "test:search-filters",
    "test:review-scope-ui",
    "test:change-set-v7",
    "test:sync-payload",
    "test:sync-v7-multidevice",
    "test:sync-v7-protocol",
    "test:sync-v8-migration",
    "test:v7-domain",
    "test:image-assets",
    "test:build-target",
    "test:platform-environment",
    "test:platform-transport",
    "test:secure-credentials",
    "test:persistent-config",
    "test:platform-lifecycle",
    "test:native-haptics",
    "test:native-files",
  ],
  source: [
    "test:architecture",
    "test:browser-launch-config",
    "test:pwa",
    "test:release-workflow",
    "test:relay",
    "test:modal",
    "test:answer-ui",
    "test:question-types",
    "test:content-block-ui",
    "test:sync-event-ui",
    "test:v7-ui",
    "test:platform-service-worker",
    "test:native-token-ui",
  ],
  integration: [
    "test:db-v7",
    "test:safari-idb",
    "test:checkpoint-extra",
    "test:sync-mock",
    "test:sync-integration",
    "test:sync-progress",
    "test:sync-compression",
    "test:sync-download-concurrency",
    "test:sync-replay-perf",
    "test:sync-install-fingerprint",
    "test:sync-history-range",
    "test:sync-tombstone-gc",
    "test:sync-multidevice-checkpoints",
    "test:sync-fresh-install-contract",
    "test:sync-note-tombstone",
    "test:sync-membership-tombstone",
    "test:sync-question-split-membership-tombstone",
    "test:sync-attempt-tombstone",
    "test:sync-practice-answer-tombstone",
    "test:sync-restore-cache-cursors",
    "test:sync-restore-cache-guard",
    "test:sync-questiongroup-tombstone",
    "test:sync-restore-full-claimed-guard",
    "test:sync-bank-delete-run-tombstone",
    "test:sync-data-races",
    "test:sync-claim-order",
    "test:sync-watermark-cache",
    "test:sync-compaction-plan-head",
    "test:sync-tombstone-retired-date",
    "test:sync-bank-reorder-folder",
    "test:sync-v7-gc",
    "test:sync-v8-history",
  ],
  // E2E tests are intentionally opt-in for fast checks. CI and release checks
  // invoke this group after installing a system Chromium.
  e2e: [
    "test:browser-smoke",
    "test:pwa-smoke",
  ],
};

export const groupConcurrency = {
  unit: 6,
  source: 6,
  integration: 2,
  e2e: 1,
};
